DATA_FOLDER = "/groups/nshomron/artemd/scratch/data/nanopore/public/filippo_lung/"
METADATA_FILENAME = 'signal_mapping_tuple.pkl'
SHUFFLE_DATA = True
metadata_pickle_file_path = "/groups/nshomron/artemd/scratch/code/Nanopore_cancer_detection/M1_M2_S1_meth_mapq_annotations_combined.pickle"
CV_FOLDS = {
    1: {
        'train_pos': (1, 11),
        'train_neg': (5, 12),
        'test_pos': (8,9,10,13),
        'test_neg': (2,3,4)
    },
    2: {
        'train_pos': (1, 9),
        'train_neg': (3, 12),
        'test_pos': (8,10,11,13),
        'test_neg': (2,4,5)
    },
    3: {
        'train_pos': (1,10),
        'train_neg': (4, 12),
        'test_pos': (8,9,11,13),
        'test_neg': (2,3,5)
    },
    4: {
        'train_pos': (10,13),
        'train_neg': (2, 12),
        'test_pos': (1,8,9,11),
        'test_neg': (3,4,5)
    },
    5: {
        'train_pos': (1,13),
        'train_neg': (2, 3),
        'test_pos': (10,8,9,11),
        'test_neg': (12,4,5)
    } 
}

SAMPLE_PATHS = ["No Sample Zero!",
                "/groups/nshomron/artemd/scratch/data/nanopore/public/filippo_lung/metadata/sample01/",
                "/groups/nshomron/artemd/scratch/data/nanopore/public/filippo_lung/metadata/sample02/",
                "/groups/nshomron/artemd/scratch/data/nanopore/public/filippo_lung/metadata/sample03/",
                "/groups/nshomron/artemd/scratch/data/nanopore/public/filippo_lung/metadata/sample04/",
                "/groups/nshomron/artemd/scratch/data/nanopore/public/filippo_lung/metadata/sample05/",
                "No Sample 06!",
                "/groups/nshomron/artemd/scratch/data/nanopore/public/filippo_lung/metadata/sample07/",
                "/groups/nshomron/artemd/scratch/data/nanopore/public/filippo_lung/metadata/sample08/",
                "/groups/nshomron/artemd/scratch/data/nanopore/public/filippo_lung/metadata/sample09/",
                "/groups/nshomron/artemd/scratch/data/nanopore/public/filippo_lung/metadata/sample10/",
                "/groups/nshomron/artemd/scratch/data/nanopore/public/filippo_lung/metadata/sample11/",
                "/groups/nshomron/artemd/scratch/data/nanopore/public/filippo_lung/metadata/sample12/",
                "/groups/nshomron/artemd/scratch/data/nanopore/public/filippo_lung/metadata/sample13/"
                ]

cont_names = ['mean_qscore_template',
 'barcode_score',
 'alignment_mapping_quality',
 'cell_type_sum_score',
 'cell_type_mean_score',
 'celltype-A549',
 'celltype-ADIPOSE_NUCLEI',
 'celltype-ADULT_LIVER',
 'celltype-AG04449',
 'celltype-AG04450',
 'celltype-AG09309',
 'celltype-AG09319',
 'celltype-AG10803',
 'celltype-AOAF',
 'celltype-AORTA',
 'celltype-BC_COLON_H12817N',
 'celltype-BC_LUNG_01-11002',
 'celltype-BC_LUNG_H12817N',
 'celltype-BC_SPLEEN_H12817N',
 'celltype-BE2_C',
 'celltype-BJ',
 'celltype-BONE_MARROW_DERIVED_MESENCHYMAL_STEM_CELL_CULTURED_CELLS',
 'celltype-BRAIN_ANGULAR_GYRUS',
 'celltype-BRAIN_ANTERIOR_CAUDATE',
 'celltype-BRAIN_CINGULATE_GYRUS',
 'celltype-BRAIN_HIPPOCAMPUS_MIDDLE',
 'celltype-BRAIN_INFERIOR_TEMPORAL_LOBE',
 'celltype-BRAIN_MID_FRONTAL_LOBE',
 'celltype-BRAIN_SUBSTANTIA_NIGRA',
 'celltype-BREAST_MYOEPITHELIAL_CELLS',
 'celltype-BREAST_VHMEC',
 'celltype-CACO-2',
 'celltype-CD14_PRIMARY_CELLS',
 'celltype-CD19_PRIMARY_CELLS_PERIPHERAL_UW',
 'celltype-CD3_PRIMARY_CELLS_CORD_BI',
 'celltype-CD3_PRIMARY_CELLS_PERIPHERAL_UW',
 'celltype-CD4+_CD25+_CD127-_TREG_PRIMARY_CELLS',
 'celltype-CD4+_CD25-_CD45RA+_NAIVE_PRIMARY_CELLS',
 'celltype-CD4+_CD25-_CD45RO+_MEMORY_PRIMARY_CELLS',
 'celltype-CD\\,4+_CD25-_IL17+_PMA-IONOMCYIN_STIMULATED_TH17_PRIMARY_CELLS',
 'celltype-CD4+_CD25-_IL17-_PMA-IONOMYCIN_STIMULATED_MACS_PURIFIED_TH_PRIMARY_CELLS',
 'celltype-CD4+_CD25INT_CD127+_TMEM_PRIMARY_CELLS',
 'celltype-CD4+_CD25-_TH_PRIMARY_CELLS',
 'celltype-CD4_MEMORY_PRIMARY_CE\\,LLS',
 'celltype-CD4_NAIVE_PRIMARY_CELLS',
 'celltype-CD56_PRIMARY_CELLS',
 'celltype-CD8_MEMORY_PRIMARY_CELLS',
 'celltype-CD8_NAIVE_PRIMARY_CELLS',
 'celltype-CHONDROCYTES_FROM_BONE_MARROW_DERIVED_MESENCHYMAL_STEM_CELL_CULTURED_CELLS',
 'celltype-COLON_SMOOTH_MUSCLE',
 'celltype-DND41',
 'celltype-DUODENUM_MUCOSA',
 'celltype-DUODENUM_SMOOTH_MUSCLE',
 'celltype-ECC-1',
 'celltype-ES-I3_CELL_LINE',
 'celltype-ES-WA7_CELL_LINE',
 'celltype-FETAL_ADRENAL_GLAND',
 'celltype-FETAL_BRAIN_FEMALE',
 'celltype-FETAL_BRAIN_MALE',
 'celltype-FETAL_HEART',
 'celltype-FETAL_INTESTINE_LARGE',
 'celltype-FETAL_INTESTINE_SMALL',
 'celltype-FETAL_KIDNEY',
 'celltype-FETAL_LUNG',
 'celltype-FETAL_MUSCLE_LEG',
 'celltype-FETAL_MUSCLE_TRUNK',
 'celltype-FETAL_PLACENTA',
 'celltype-FETAL_STOMACH',
 'celltype-FETAL_THYMUS',
 'celltype-GASTRIC',
 'celltype-GLIOBLA',
 'celltype-GM06990',
 'celltype-GM12864',
 'celltype-GM12865',
 'celltype-GM12891',
 'celltype-GM12892',
 'celltype-H1_BMP4_DERIVED_MESENDODERM_CULTURED_CELLS',
 'celltype-H1_BMP4_DERIVED_TROPHOBLAST_CULTURED_CELLS',
 'celltype-H1_DERIVED_MESENCHYMAL_STEM_CELLS',
 'celltype-H1_DERIVED_NEURONAL_PROGENITOR_CULTURED_CELLS',
 'celltype-H1-HESC',
 'celltype-H7-HESC',
 'celltype-H9_DERIVED_NEURONAL_PROGENITOR_CULTURED_CELLS',
 'celltype-H9_DERIVED_NEURON_CULTURED_CELLS',
 'celltype-H9ES',
 'celltype-HAC',
 'celltype-HA-SP',
 'celltype-HBMEC',
 'celltype-HCFAA',
 'celltype-HCM',
 'celltype-HCPEPIC',
 'celltype-HCT-116',
 'celltype-HEEPIC',
 'celltype-HEK293',
 'celltype-HEPG2',
 'celltype-HESC_DERIVED_CD184+_ENDODERM_CULTURED_CELLS',
 'celltype-HESC_DERIVED_CD56+_ECTODERM_CULTURED_CELLS',
 'celltype-HESC_DERIVED_CD56+_MESODERM_CULTURED_CELLS',
 'celltype-HFF',
 'celltype-HFF-MYC',
 'celltype-HL-60',
 'celltype-HMEC',
 'celltype-HMF',
 'celltype-HPAF',
 'celltype-HPF',
 'celltype-HRE',
 'celltype-HRPEPIC',
 'celltype-HSMM',
 'celltype-HSMMTUBE',
 'celltype-HUES48_CELL_LINE',
 'celltype-HUES64_CELL_LINE',
 'celltype-HUES6_CELL_LINE',
 'celltype-HUVEC',
 'celltype-IMR90',
 'celltype-IPS-15B_CELL_LINE',
 'celltype-IPS-18_CELL_LINE',
 'celltype-IPS-20B_CELL_LINE',
 'celltype-IPS_DF_19.11_CELL_LINE',
 'celltype-IPS_DF_6.9_CELL_LINE',
 'celltype-K562',
 'celltype-LEFT_VENTRICLE',
 'celltype-LHCN-M2',
 'celltype-MCF-7',
 'celltype-MESENCHYMAL_STEM_CELL_DERIVED_ADIPOCYTE_CULTURED_CELLS',
 'celltype-MOBILIZED_CD34_PRIMARY_CELLS_FEMALE',
 'celltype-MOBILIZED_CD34_PRIMARY_CELLS_MALE',
 'celltype-MONOCYTES-CD14+_RO01746',
 'celltype-NB4',
 'celltype-NH-A',
 'celltype-NHDF-AD',
 'celltype-NHDF-NEO',
 'celltype-NHEK',
 'celltype-NHLF',
 'celltype-NT2-D1',
 'celltype-OSTEOBL',
 'celltype-OVARY',
 'celltype-PANC-1',
 'celltype-PANISLETS',
 'celltype-PENIS_FORESKIN_FIBROBLAST_PRIMARY_CELLS_SKIN01',
 'celltype-PENIS_FORESKIN_FIBROBLAST_PRIMARY_CELLS_SKIN02',
 'celltype-PENIS_FORESKIN_KERATINOCYTE_PRIMARY_CELLS_SKIN02',
 'celltype-PENIS_FORESKIN_KERATINOCYTE_PRIMARY_CELLS_SKIN03',
 'celltype-PENIS_FORESKIN_M\\,ELANOCYTE_PRIMARY_CELLS_SKIN01',
 'celltype-PENIS_FORESKIN_MELANOCYTE_PRIMARY_CELLS_SKIN03',
 'celltype-PERIPHERAL_BLOOD_MONONUCLEAR_PRIMARY_CELLS',
 'celltype-PLACENTA_AMNION',
 'celltype-PROGFIB',
 'celltype-PSOAS_MUSCLE_OC',
 'celltype-RECTAL_MUCOSA.DONOR_29',
 'celltype-RECTAL_MUCOSA.DONOR_31',
 'celltype-RECTAL_SMOOTH_MUSCLE',
 'celltype-RIGHT_ATRIUM',
 'celltype-RIGHT_VENTRICLE',
 'celltype-RPTEC',
 'celltype-SAEC',
 'celltype-SIGMOID_COLON',
 'celltype-SKELETAL_MUSCLE_FEMALE',
 'celltype-SKELETAL_MUSCLE_MALE',
 'celltype-SK-N-MC',
 'celltype-SK-N-SH',
 'celltype-SK-N-SH_RA',
 'celltype-SMALL_INTESTINE_OC',
 'celltype-STOMACH_MUCOSA',
 'celltype-STOMACH_SMOOTH_MUSCLE',
 'celltype-T-47D',
 'celltype-THYMUS',
 'celltype-WERI-RB-1',
 'celltype-WI-38',
 'methylation-Adipocytes',
 'methylation-Endothel',
 'methylation-Smooth-Musc',
 'methylation-Bladder-Ep',
 'methylation-Blood-B',
 'methylation-Blood-Granul',
 'methylation-Blood-Mono+Macro',
 'methylation-Blood-NK',
 'methylation-Blood-T',
 'methylation-Eryth-prog',
 'methylation-Bone-Osteob',
 'methylation-Breast-Basal-Ep',
 'methylation-Breast-Luminal-Ep',
 'methylation-Neuron',
 'methylation-Oligodend',
 'methylation-Head-Neck-Ep',
 'methylation-Gastric-Ep',
 'methylation-Small-Int-Ep',
 'methylation-Colon-Ep',
 'methylation-Heart-Cardio',
 'methylation-Fallopian-Ep',
 'methylation-Kidney-Ep',
 'methylation-Heart-Fibro',
 'methylation-Colon-Fibro',
 'methylation-Dermal-Fibro',
 'methylation-Liver-Hep',
 'methylation-Lung-Ep-Alveo',
 'methylation-Lung-Ep-Bron',
 'methylation-Ovary-Ep',
 'methylation-Pancreas-Acinar',
 'methylation-Pancreas-Duct',
 'methylation-Pancreas-Alpha',
 'methylation-Pancreas-Beta',
 'methylation-Pancreas-Delta',
 'methylation-Prostate-Ep',
 'methylation-Epid-Kerat',
 'methylation-Gallbladder',
 'methylation-Skeletal-Musc',
 'methylation-Thyroid-Ep']

cat_names = ['alignment_genome',
            'alignment_direction',
            'translated_chrom',
            'aberrant_processed_transcript',
            'supercontig',
            'loss_gene',
            'lincRNA_gene',
            'snRNA_gene',
            'three_prime_UTR',
            'nc_primary_transcript',
            'miRNA_gene',
            'rRNA_gene',
            'snRNA',
            'biological_region',
            'NMD_transcript_variant',
            'TF_binding_site',
            'promoter_flanking_region',
            'open_chromatin_region']
